# Generated by Django 3.2.8 on 2022-02-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20220226_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='comment',
        ),
    ]
