# Generated by Django 3.2.8 on 2022-02-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_rename_description_task_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='url',
            new_name='commit',
        ),
    ]
