# Generated by Django 3.2.8 on 2022-02-18 03:46

from django.db import migrations, models

from project.models import Project

projects = [
    {"name": "lezin", "description": "SAAS de mise en relation dans le domaine du voyage"},
    {"name": "ekwali.cm", "description": "Site de l'agence"},
    {"name": "squad offshore", "description": "/"},
]

def load_fixture(apps, schema_editor):
    for project in projects:
        new_program, _ = Project.objects.get_or_create(name=project["name"])
        new_program.description = project["description"]
        new_program.save()

def unload_fixture(apps, schema_editor):
    """Brutally deleting all entries for this model..."""

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
